//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2019 Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t entry_point(int32_t a1);
int32_t function_1c(void);
int32_t function_46(int32_t result);

// --------------------- Global Variables ---------------------

int32_t g1 = 71;

// ------------------------ Functions -------------------------

// Address range: 0x0 - 0x1c
int32_t entry_point(int32_t a1) {
    // 0x0
    bool v1; // cpsr_z
    return v1 ? 0 : a1;
}

// Address range: 0x1c - 0x46
int32_t function_1c(void) {
    // 0x1c
    *(int32_t *)0x40021018 = (int32_t)&g1;
    *(int32_t *)0x40011004 = 0x44434444;
    int32_t v1 = 0x4001100c; // r6
    int32_t v2 = 0x4001100c; // bp+34
    while (true) {
        // 0x34
        *(int32_t *)v2 = 0;
        *(int32_t *)v1 = 0x2000;
        v2 = v1;
    }
}

// Address range: 0x46 - 0x4e
int32_t function_46(int32_t result) {
    // 0x46
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.4.3)
// Detected functions: 3
// Decompilation date: 2019-03-30 15:57:28
